query GetCreatedDVs @live(interval: 30000) {
  clusterCreateds(orderBy: timestamp, orderDirection: desc) {
    id
    timestamp
    txHash
    splitAddress
    averageAuctionScore
    winners {
      id
      nodeOp {
        nodeOpAddr
      }
      duration
      discountRate
      bidPrice
      auctionScore
      auctionType
      bidStatus
    }
  }
}
