query GetPendingBids @live {
  bidPlaceds(where: {bidStatus: Pending}, orderBy: timestamp, orderDirection: asc) {
    nodeOp {
      nodeOpAddr
    }
    discountRate
    duration
    bidPrice
    uint256AuctionScore
    bidStatus
    timestamp
    txHash
  }
}
